import Image from 'next/image';
import Head from 'next/head';
import { useAuth } from '../lib/auth';
import styles from '../styles/Home.module.css';

export default function Home() {
  const auth = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Job Trackr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/Logo with no text.svg"
          alt="Job trackr logo"
          width={60}
          height={60}
        />
        <p className={styles.description}>
          Job Tracker is the easiest way to organize and keep track of your job
          application process. It&apos;s still a work-in-progress, but you can
          try it out by logging in.
        </p>

        <button onClick={(e) => auth.signinWithGithub()}>
          Sign In With GitHub
        </button>
        <p>
          Current user: <code>{auth?.user ? auth.user.email : 'None'}</code>
        </p>
        {auth?.user && (
          <button onClick={(e) => auth.signout()}>Sign Out</button>
        )}
      </main>
    </div>
  );
}
